function v = phi( coef, r, s, flag )
    v = zeros( length( r ), 1 );

    v = coef( 1, flag) * 1 + ... 
        coef( 2, flag) * r + ...
        coef( 3, flag) * s + ...
        coef( 4, flag) * r.*r + ...
        coef( 5, flag) * r.*s + ...
        coef( 6, flag) * s.*s;
end 